### ISSUE TITLE
rustbot always thinks @oli-obk is a new contributor

### ISSUE THREAD

**Issue by saethlin** [rust-lang/triagebot#1689] opened 2023-04-16 19:11 UTC
Reporting this because the bot _also_ failed to ping rust-lang/miri here: https://github.com/rust-lang/rust/pull/109938#issuecomment-1510407389

Examples of the bot thinking @oli-obk is a new contributor:

https://github.com/rust-lang/rust/pull/109938
https://github.com/rust-lang/rust/pull/109115
https://github.com/rust-lang/rust/pull/108860
https://github.com/rust-lang/rust/pull/110315

It looks like maybe all the cases where Oli doesn't get the welcome message are PRs that start with a `r? @ghost` in the PR description.

**Comment by oli-obk** [comment] 2023-04-16 19:41
I tried fixing this by setting a correct email address in https://github.com/rust-lang/rust/pull/108035 but it turns out github doesn't grok their own custom address either. So I'd need to change that again or make a commit with it.

**Comment by ehuss** [comment] 2023-04-16 19:41
It looks to be some issue on GitHub's side.  https://api.github.com/repos/rust-lang/rust/commits?author=oli-obk is returning an empty array. I don't see anything obvious to explain why (the commit objects using other queries like https://api.github.com/repos/rust-lang/rust/commits?sha=241c6a4a616010382aefe297c69a26fb5a22dd06 clearly show the author field as `"oli-obk"`).  Maybe it is caused by the large number of mailmap entries? Or maybe changes in their email address had issues with the index? I'm not sure how GitHub maps commits to GitHub accounts.

We may need to change it back to use the search endpoint (`/search/commits?q=repo:rust-lang/rust+author:oli-obk`), which seems to work correctly.

**Comment by Nilstrieb** [comment] 2023-04-18 04:49
@durin42 is experiencing the same welcomingness: https://github.com/rust-lang/rust/pull/110455#issuecomment-1511532036

**Comment by ehuss** [comment] 2023-04-18 15:32
@Nilstrieb I think their email address does not match their email address in GitHub, so it is not possible to know if they have committed before or not.

**Comment by RalfJung** [comment] 2023-07-31 10:21
@rytheo seems to also be "always new": https://github.com/rust-lang/rust/pull/114257

**Comment by ehuss** [comment] 2023-07-31 19:50
Posted #1713 with a fix which seems to work for both rytheo and oli-obk.

**Closed** 2023-09-04 23:18 UTC
Labels: bug, A-assign-PR
