### ISSUE TITLE
The "Ready" shortcut should work on pull request review comments

### ISSUE THREAD

**Issue by jyn514** [rust-lang/triagebot#1614] opened 2022-05-03 04:03 UTC
Right now it only works on top-level comments, not review comments.

_Originally posted by @rustbot in https://github.com/rust-lang/rust/issues/96584#issuecomment-1115720413_

**Comment by apiraino** [comment] 2022-06-27 22:11
I'm trying to reproduce this on a local triagebot installation but so far no success.

@ehuss any suggestion? I see many occurrences of this in the rust-lang/rust pull requests but I'm blind since I don't have access to the logs (and we don't have a test repository, do we?)

**Comment by Mark-Simulacrum** [comment] 2022-06-27 22:29
I believe this is fixed -- I added logic but failed to close this issue (probably due to not knowing about it) to resolve this in https://github.com/rust-lang/triagebot/pull/1619.

**Closed by Mark-Simulacrum** 2022-06-27 22:29 UTC

**Comment by apiraino** [comment] 2022-06-28 07:46
oh. Now I see :)
